### ISSUE TITLE
Information about points

### ISSUE THREAD

**Issue by TheSkids** [pudds/110yards#1]
How do we know what different stats equal for points?

**Comment by pudds** [comment]
It's simplistic for now, but you can view the scoring settings in two places:

Before the league has started/drafted, you can go to Commissioner > Change League Options

From there, you can view the 3 options, and change the one for your league.

At any time, the scoring type is also shown on the league page, under the league name.  You can click it to view that specific scoring type.

For quick reference, here are the 3 scoring type pages:

[Standard](http://110yards.ca/scoring/1)

[Standard PPR](http://110yards.ca/scoring/2)

[Admin's choice](http://110yards.ca/scoring/3)
