### ISSUE TITLE
Draft Roster Addition Issues

### ISSUE THREAD

**Issue by 49ersAlouettes** [pudds/110yards#10]
**Describe the bug**
1) I cannot add D'haquille Williams to the owner's team that drafted him. The rest of the players drafted by this owner were added with no problem.
2) I cannot add any players to another owner's team at all. 

**To Reproduce**
1. Go to D'haquille Williams and press the "+" to add him and nothing happens. Same thing for the other owner's team - no matter who I try to add

**Expected behavior**
I expected the players to be added to the rosters - just like they did for the other owners.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Desktop
 - Chrome
 - Not Sure on Version

**Additional context**
Would like to have this resolved in order to get lineups in by tonight's game. Thank you.

**Comment by 49ersAlouettes** [comment]
Our League's name is Granite State Maple Leaves

**Comment by 49ersAlouettes** [comment]
I tried on my iphone as well. Same results.

Also,
Radrums44... is the team that D Williams will not add to

Canadian Bacon... is the team that no players will add to

**Comment by pudds** [comment]
This looks like it might be a javascript issue with his name.  I'll take
care of it right away.

**Comment by pudds** [comment]
Is this just in draft mode?  If so, I'd recommend you skip over him and
have the manager add him manually post-draft - I just tested and he works
ok when adding outside the draft.  I'll fix the draft bug too, but the
workaround will be quicker.

**Comment by 49ersAlouettes** [comment]
Thanks! You made a lot of former fantaseh users very happy here in NH. Can’t wait to get this underway

**Comment by pudds** [comment]
This should be working now.
