### ISSUE TITLE
I've been trying to access the site on my mobile app.  I can't see the items in the header row such as League, My Team, Players.  I can see the 1st 2 through other paths but I can't get to Players at all.  I'm using a Samsung Galaxy S7.

### ISSUE THREAD

**Issue by yukonriderfan** [pudds/110yards#13]

**Comment by pudds** [comment]
You can view the menu by clicking the menu icon in the upper right hand corner of the site (aka the hamburger menu):

![image](https://user-images.githubusercontent.com/5611490/43795558-5510a222-9a47-11e8-8653-5d0df0cdb0d7.png)

**Comment by yukonriderfan** [comment]
Thank you.  I was also having a hard time in accessing it as it was right behind the ellipse for my Samsung internet.  I was able to slide the screen to the left and access it.


________________________________
