### ISSUE TITLE
waivers

### ISSUE THREAD

**Issue by nukes2** [pudds/110yards#15]
waivers period is over and we still can't add players. whassup?

**Comment by pudds** [comment]
Thanks for the reminder.  They are done now.

Hoping to have this process kick off automatically for next week.

**Comment by nukes2** [comment]
yep, that did it. where are you? Ontario? 

    On Wednesday, July 11, 2018 10:42 AM, pudds <notifications@github.com> wrote:
 

 Thanks for the reminder. They are done now.

Hoping to have this process kick off automatically for next week.
