### ISSUE TITLE
Total score discrepancy between Matchup and League pages

### ISSUE THREAD

**Issue by DamoQ** [pudds/110yards#7]
**Describe the bug**
The matchup score on the League page shows 66.10 for my opponent, and 76.40 for myself. Above the "Proj" column for myself it says "6/6 played", but for my opponent it says "7/6 played."

On the League page, the matchup score give 77.10 to my opponent, and 76.40 to myself.

So, it seems the matchup score is double counting for my opponent on the League page.

**To Reproduce**
1. Go to League page: http://110yards.ca/league/4
2. Observe Week 1 score for "Bo Knows!" vs "Going In For D’haquille"
3. Go to Matchup page: http://110yards.ca/league/4/matchup/77
4. Observe the tabulated score is different from the League page, but does correspond to the sum of player scores.

**Expected behavior**
The Week 1 matchup score for all players should be consistent across the different site pages.

**Screenshots**

**Desktop (please complete the following information):**
Chrome Version 67.0.3396.87

**Smartphone (please complete the following information):**
Iphone 7

**Additional context**

**Comment by pudds** [comment]
Thanks for the report - for some reason, a player was added to Bo Knows twice - your league is one of the first to have signed up, so I think you were affected by a bug which was later fixed (I'll have to monitor that to make sure though).

I've resolved the issue and the score is correct now.
